/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saúde da aplicação */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca municípios por nome (autocomplete)
         * @description Insensível a caixa, acento, apóstrofo e hífen; palavras em qualquer ordem.
         *     Ordenação: nome igual ao termo, depois prefixo, depois contém; empate por população desc.
         */
        get: operations["buscarMunicipios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumo do Censo 2022 de um município */
        get: operations["obterMunicipio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ufs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista das 27 UFs ordenadas por nome */
        get: operations["listarUfs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ufs/{sigla}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Totais do Censo 2022 de uma UF */
        get: operations["obterUf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ufs/{sigla}/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Municípios da UF ranqueados por densidade (desc), paginados */
        get: operations["rankingMunicipiosUf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Problem Details (RFC 9457) */
        Problema: {
            /** @default about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
        UfRef: {
            /** @example 35 */
            codigo: string;
            /** @example SP */
            sigla: string;
            /** @example São Paulo */
            nome: string;
        };
        MunicipioSugestao: {
            /** @example 3550308 */
            codigo: string;
            /** @example São Paulo */
            nome: string;
            uf: components["schemas"]["UfRef"];
            /**
             * @description "Nome - SIGLA"
             * @example São Paulo - SP
             */
            rotulo: string;
        };
        MunicipioResumo: {
            codigo: string;
            nome: string;
            uf: components["schemas"]["UfRef"];
            /** @example 11451999 */
            populacao: number;
            /** @description 2 casas decimais */
            area_km2: number;
            /** @description null quando a área é 0 */
            densidade_hab_km2: number | null;
            /** @description urbanos + rurais + sem_classificacao = total */
            setores: {
                total: number;
                urbanos: number;
                rurais: number;
                sem_classificacao: number;
            };
            sexo: {
                homens: number;
                mulheres: number;
                /** @description max(populacao - homens - mulheres, 0) */
                nao_informado: number;
                /** @description sobre homens + mulheres; null se a soma for 0 */
                percentual_homens: number | null;
                percentual_mulheres: number | null;
            };
        };
        UfResumo: components["schemas"]["UfRef"] & {
            populacao: number;
            area_km2: number;
            /** @description soma(pop) / soma(área) da UF */
            densidade_hab_km2: number | null;
            total_municipios: number;
        };
        ItemRanking: {
            /** @description posição global na UF (não o índice na página) */
            posicao: number;
            codigo: string;
            nome: string;
            populacao: number;
            area_km2: number;
            densidade_hab_km2: number | null;
        };
        MetaPaginacao: {
            pagina: number;
            por_pagina: number;
            total: number;
            total_paginas: number;
        };
    };
    responses: {
        /** @description Representação não mudou desde o `ETag` informado (sem corpo) */
        NaoModificado: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Recurso inexistente */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Não encontrado",
                 *       "status": 404,
                 *       "detail": "Município não encontrado."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Parâmetros inválidos */
        Validacao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"] & {
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        /**
         * @description Sigla da UF (maiúsculas ou minúsculas)
         * @example SP
         */
        Sigla: string;
    };
    requestBodies: never;
    headers: {
        /** @description Identificador da representação; reenviar em `If-None-Match`. */
        ETag: string;
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pronta para atender */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    buscarMunicipios: {
        parameters: {
            query: {
                /** @example sao paulo */
                q: string;
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sugestões (lista vazia quando nada é encontrado) */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MunicipioSugestao"][];
                    };
                };
            };
            304: components["responses"]["NaoModificado"];
            422: components["responses"]["Validacao"];
        };
    };
    obterMunicipio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 3550308 */
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumo do município */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MunicipioResumo"];
                    };
                };
            };
            304: components["responses"]["NaoModificado"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    listarUfs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UFs */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UfRef"][];
                    };
                };
            };
            304: components["responses"]["NaoModificado"];
        };
    };
    obterUf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Sigla da UF (maiúsculas ou minúsculas)
                 * @example SP
                 */
                sigla: components["parameters"]["Sigla"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumo da UF */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UfResumo"];
                    };
                };
            };
            304: components["responses"]["NaoModificado"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    rankingMunicipiosUf: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Sigla da UF (maiúsculas ou minúsculas)
                 * @example SP
                 */
                sigla: components["parameters"]["Sigla"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página do ranking (`data` vazio quando a página passa do fim) */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ItemRanking"][];
                        meta: components["schemas"]["MetaPaginacao"];
                    };
                };
            };
            304: components["responses"]["NaoModificado"];
            404: components["responses"]["NaoEncontrado"];
            422: components["responses"]["Validacao"];
        };
    };
}
